-- ══════════════════════════════════════════════════════════════════════
-- MIGRATION — Referral program + gamified leaderboard (v2, RPC-based)
-- Applies to: Supabase project (SQL Editor → New query → paste → Run)
--
-- DESIGN:
--   * Every user gets a personal referral_code on their profiles row.
--   * Friends click  yaadadz.com/invite/<CODE>  (or  ?ref=<CODE>).
--   * On signup the new user's browser calls send_referral(p_code) →
--     referrer +50 Yaad Points & +1 referral counter,
--     invitee gets +25 welcome points.
--   * referral_events = full trackable audit trail (who referred whom, when).
--   * referral_leads   = the EMAIL LIST (pre-signup email capture)
--   * weekly_winners   = top 5 referrers per week (prize record for the 🏆)
--   * reset_weekly_referrals() snapshots the top 5 then zeroes the week.
--     Called weekly by .github/workflows/referral-weekly-reset.yml.
--
-- Browser entry points:
--   js/core.js  (ref capture + RPC calls) → js/auth-account.js (signup tie)
--   js/search-ai.js (renderReferralSpot + leaderboard)
-- ══════════════════════════════════════════════════════════════════════

-- ── 1. Extend profiles with referral + gamification columns ─────────────
alter table public.profiles add column if not exists yaad_points         bigint not null default 0;
alter table public.profiles add column if not exists total_referrals     int    not null default 0;
alter table public.profiles add column if not exists referrals_this_week int    not null default 0;
alter table public.profiles add column if not exists last_week_winner    timestamptz;            -- when the user last wore the 🏆
alter table public.profiles add column if not exists best_week_rank      int;                    -- best weekly rank ever (1–5)
alter table public.profiles add column if not exists referral_code       text;                   -- THEIR OWN shareable code
alter table public.profiles add column if not exists referred_by_code    text;                   -- which code brought THEM in

-- unique on referral_code (idempotent add)
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'profiles_referral_code_key'
  ) then
    alter table public.profiles add constraint profiles_referral_code_key unique (referral_code);
  end if;
end $$;

-- Backfill existing members with deterministic codes (safe, idempotent).
update public.profiles
   set referral_code = 'YA' || upper(substr(md5(id::text), 1, 8))
 where referral_code is null;

-- ── 2. Trackable audit trail: referral_events (one per new member) ─────
create table if not exists public.referral_events (
  id          bigint generated by default as identity primary key,
  code        text not null,
  referrer_id uuid not null references public.profiles(id) on delete cascade,
  invitee_id  uuid not null references public.profiles(id) on delete cascade,
  created_at  timestamptz not null default now(),
  unique (invitee_id)                              -- each person referred once
);
create index if not exists idx_ref_events_referrer on public.referral_events(referrer_id);
create index if not exists idx_ref_events_code     on public.referral_events(code);

-- ── 3. EMAIL LIST: referral_leads (pre-signup email capture) ────────────
create table if not exists public.referral_leads (
  id          bigint generated by default as identity primary key,
  email       text not null,
  ref_code    text not null,
  referrer_id uuid references public.profiles(id) on delete set null,
  claimed     boolean not null default false,
  claimed_by  uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);
create index if not exists idx_leads_ref_code on public.referral_leads(ref_code);
create index if not exists idx_leads_email    on public.referral_leads(lower(email));

-- ── 4. Top-5 prize record: weekly_winners ───────────────────────────────
create table if not exists public.weekly_winners (
  id           bigint generated by default as identity primary key,
  week_start   date not null,
  rank         int  not null check (rank between 1 and 5),
  user_id      uuid references public.profiles(id) on delete cascade,
  referrals    int  not null default 0,
  prize_awarded boolean not null default false,
  created_at   timestamptz not null default now(),
  unique (week_start, rank)
);
create index if not exists idx_weekly_winner_user on public.weekly_winners(user_id);
-- ══════════════════════════════════════════════════════════════════════
-- 5. AUTO-ASSIGN A REFERRAL CODE on every new profile row
-- ══════════════════════════════════════════════════════════════════════
create or replace function public.assign_referral_code()
returns trigger
language plpgsql security definer
set search_path = public
as $$
begin
  if new.referral_code is null then
    new.referral_code := 'YA' || upper(substr(md5(new.id::text), 1, 8));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_assign_referral_code on public.profiles;
create trigger trg_assign_referral_code
  before insert on public.profiles
  for each row execute function public.assign_referral_code();

-- ══════════════════════════════════════════════════════════════════════
-- 6. send_referral(p_code) — atomic, secure claim at signup
--    Uses auth.uid() so a member can only claim for THEMSELVES.
--    Idempotent: already-referred users get a friendly skip.
-- ══════════════════════════════════════════════════════════════════════
create or replace function public.send_referral(p_code text)
returns jsonb
language plpgsql security definer
set search_path = public
as $$
declare
  v_caller uuid := auth.uid();
  v_ref   public.profiles%rowtype;
  v_lead  public.referral_leads%rowtype;
  v_claim uuid;
begin
  if v_caller is null then
    return jsonb_build_object('ok', false, 'error', 'not_authenticated');
  end if;
  if p_code is null or btrim(p_code) = '' then
    return jsonb_build_object('ok', false, 'error', 'missing_code');
  end if;

  select * into v_ref
    from public.profiles
   where referral_code = upper(btrim(p_code));
  if not found then
    return jsonb_build_object('ok', false, 'error', 'code_not_found');
  end if;
  if v_ref.id = v_caller then
    return jsonb_build_object('ok', false, 'error', 'self_referral');
  end if;

  -- already referred via any code → friendly skip (idempotent re-visits)
  if exists (select 1 from public.profiles where id = v_caller and referred_by_code is not null) then
    return jsonb_build_object('ok', false, 'status', 'already_referred');
  end if;

  -- Trackable event. Inserting IS the claim: a lost race (conflict) returns
  -- no row, so awards below can never fire twice.
  insert into public.referral_events (code, referrer_id, invitee_id)
  values (v_ref.referral_code, v_ref.id, v_caller)
  on conflict (invitee_id) do nothing
  returning invitee_id into v_claim;

  if v_claim is not null then
    -- attribution + awards (only reached when the insert actually happened)
    update public.profiles set referred_by_code = v_ref.referral_code where id = v_caller;

    update public.profiles
       set yaad_points         = yaad_points + 50,
           total_referrals     = total_referrals + 1,
           referrals_this_week = referrals_this_week + 1
     where id = v_ref.id;

    -- invitee welcome bonus
    update public.profiles set yaad_points = yaad_points + 25 where id = v_caller;

    -- claim a matching emailed lead so the email list gets a verified member
    select * into v_lead
      from public.referral_leads
     where ref_code = v_ref.referral_code and claimed = false
       and lower(email) = (select lower(email) from auth.users where id = v_caller)
     order by created_at asc limit 1;
    if found then
      update public.referral_leads
         set claimed = true, claimed_by = v_caller
       where id = v_lead.id;
    end if;

    return jsonb_build_object('ok', true, 'status', 'claimed',
      'bonus', 50, 'message', 'Referral credited! You both earned +50 Yaad Points 🎉');
  end if;

  return jsonb_build_object('ok', false, 'status', 'already_claimed');
end;
$$;

revoke execute on function public.send_referral(text) from public;
grant execute on function public.send_referral(text) to authenticated;
-- ══════════════════════════════════════════════════════════════════════
-- 7. capture_referral_lead(p_code, p_email) — EMAIL LIST builder.
--    Safe for anon (no auth needed) — one email per code, validated shape.
-- ══════════════════════════════════════════════════════════════════════
create or replace function public.capture_referral_lead(p_code text, p_email text)
returns jsonb
language plpgsql security definer
set search_path = public
as $$
declare
  v_ref   public.profiles%rowtype;
  v_email text := lower(btrim(coalesce(p_email, '')));
begin
  if p_code is null or btrim(p_code) = '' then
    return jsonb_build_object('ok', false, 'error', 'missing_code');
  end if;
  if v_email = '' or v_email !~ '^[^@\s]+@[^@\s]+[.][^@\s]+$' then
    return jsonb_build_object('ok', false, 'error', 'bad_email');
  end if;

  select * into v_ref
    from public.profiles
   where referral_code = upper(btrim(p_code));
  if not found then
    return jsonb_build_object('ok', false, 'error', 'code_not_found');
  end if;

  if exists (select 1 from public.referral_leads
              where lower(email) = v_email and ref_code = v_ref.referral_code) then
    return jsonb_build_object('ok', true, 'status', 'already_captured', 'referrer_name', v_ref.name);
  end if;

  insert into public.referral_leads (email, ref_code, referrer_id)
  values (v_email, v_ref.referral_code, v_ref.id);

  return jsonb_build_object('ok', true, 'status', 'captured', 'referrer_name', v_ref.name);
end;
$$;

revoke execute on function public.capture_referral_lead(text, text) from public;
grant execute on function public.capture_referral_lead(text, text) to anon, authenticated;

-- ══════════════════════════════════════════════════════════════════════
-- 8. get_leaderboard(p_limit) — correct ordering + tier labels.
--    Score = yaad_points (50/ref). Ties broken by total_referrals.
-- ══════════════════════════════════════════════════════════════════════
create or replace function public.get_leaderboard(p_limit int default 50)
returns table (
  id uuid, name text, yaad_points bigint, total_referrals int,
  referrals_this_week int, last_week_winner timestamptz, best_week_rank int,
  tier text
)
language plpgsql security definer
set search_path = public
as $$
begin
  return query
    select p.id, p.name, p.yaad_points, p.total_referrals, p.referrals_this_week,
           p.last_week_winner, p.best_week_rank,
           case
             when p.total_referrals >= 50 then '👑 Legend'
             when p.total_referrals >= 25 then '💎 Diamond'
             when p.total_referrals >= 10 then '⭐ Star'
             when p.total_referrals >= 5  then '🤝 Friend'
             when p.total_referrals >= 1  then '🌱 Newbie'
             else 'Rookie'
           end as tier
      from public.profiles p
     where p.yaad_points > 0 or p.total_referrals > 0
     order by p.yaad_points desc, p.total_referrals desc, p.referrals_this_week desc
     limit greatest(1, least(coalesce(p_limit, 50), 100));
end;
$$;

revoke execute on function public.get_leaderboard(int) from public;
grant execute on function public.get_leaderboard(int) to anon, authenticated;
-- ══════════════════════════════════════════════════════════════════════
-- 9. reset_weekly_referrals(p_week_start) — snapshots TOP 5 winners, then
--    zeroes the week. Called by the weekly GitHub Actions cron with the
--    service_role key (service-role only — never callable by clients).
-- ══════════════════════════════════════════════════════════════════════
create or replace function public.reset_weekly_referrals(p_week_start date default current_date)
returns jsonb
language plpgsql security definer
set search_path = public
as $$
declare
  v_rows int;
begin
  -- record the just-ended week's top 5 (most referrals this week)
  insert into public.weekly_winners (week_start, rank, user_id, referrals)
  select p_week_start, rk, id, num
    from (
      select id, referrals_this_week as num,
             row_number() over (order by referrals_this_week desc, yaad_points desc) as rk
        from public.profiles
       where referrals_this_week > 0
    ) t
   where rk <= 5
  on conflict (week_start, rank) do nothing;
  get diagnostics v_rows = row_count;

  -- 🏆 #1 wears the crown; everyone in the top 5 keeps their best rank
  update public.profiles p
     set last_week_winner = now(),
         best_week_rank   = least(coalesce(p.best_week_rank, 99), w.rank)
    from public.weekly_winners w
   where w.week_start = p_week_start and w.user_id = p.id and w.rank = 1;

  update public.profiles p
     set best_week_rank = least(coalesce(p.best_week_rank, 99), w.rank)
    from public.weekly_winners w
   where w.week_start = p_week_start and w.user_id = p.id and w.rank > 1;

  -- start the new week fresh
  update public.profiles set referrals_this_week = 0;

  return jsonb_build_object('ok', true, 'winners_recorded', v_rows);
end;
$$;

revoke execute on function public.reset_weekly_referrals(date) from public;
grant execute on function public.reset_weekly_referrals(date) to service_role;

-- ══════════════════════════════════════════════════════════════════════
-- 10. RLS policies + grants
--     Writes happen ONLY inside the security-definer functions above, so
--     public/anonymous clients get read-only access (leaderboard + their
--     own tracking rows).
-- ══════════════════════════════════════════════════════════════════════
alter table public.referral_events enable row level security;
alter table public.referral_leads   enable row level security;
alter table public.weekly_winners   enable row level security;

-- Leaderboard read (anon + auth) — column-granted so email/phone stay private.
grant select (id, name, yaad_points, total_referrals, referrals_this_week,
              last_week_winner, best_week_rank, referral_code)
       on public.profiles to anon, authenticated;

drop policy if exists "anyone reads profiles leaderboard" on public.profiles;
create policy "anyone reads profiles leaderboard" on public.profiles
  for select using (true);

-- Tracking rows: members can see their OWN referral events + email leads.
drop policy if exists "owner reads own referral events" on public.referral_events;
create policy "owner reads own referral events" on public.referral_events
  for select using (referrer_id = auth.uid());

drop policy if exists "owner reads own referral leads" on public.referral_leads;
create policy "owner reads own referral leads" on public.referral_leads
  for select using (referrer_id = auth.uid());

-- Past weekly winners are public (that's the leaderboard history).
drop policy if exists "anyone views weekly winners" on public.weekly_winners;
create policy "anyone views weekly winners" on public.weekly_winners
  for select using (true);

-- ── Cleanup: drop the broken v1 experiment table (never had consumers) ──
drop table if exists public.referrals;